apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
type: Opaque
stringData:
  databaseUrl: "${DATABASE_URL}"
  secretKey: "${SECRET_KEY}"
  algorithm: "HS256"
  accessTokenExpireMinutes: "30"
  backendCorsOrigins: '["http://34.16.87.197", "http://localhost:3000", "http://127.0.0.1:3000", "http://127.0.0.1:8000/", "http://localhost:30000", "http://localhost:30001"]'
  geminiApiKey: "${GEMINI_API_KEY}"
