apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  databaseUrl: {{ .Values.secrets.databaseUrl | quote }}
  secretKey: {{ .Values.secrets.secretKey | quote }}
  algorithm: {{ .Values.secrets.algorithm | quote }}
  accessTokenExpireMinutes: {{ .Values.secrets.accessTokenExpireMinutes | quote }}
  geminiApiKey: {{ .Values.secrets.geminiApiKey | quote }}
  nextPublicGeminiApiKey: {{ .Values.secrets.nextPublicGeminiApiKey | quote }}
  betterAuthSecret: {{ .Values.secrets.betterAuthSecret | quote }}
  betterAuthUrl: {{ .Values.secrets.betterAuthUrl | quote }}
  backendCorsOrigins: {{ .Values.secrets.backendCorsOrigins | quote }}